Ref: code style, Readme

diff --git a/daisync b/daisync
--- a/daisync
+++ b/daisync
@@ -1,19 +1,37 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
 trap "exit 1" TERM
-function helpme {
+function die {
+	# 20251225
 	if [ $# -gt 0 ]
 	then
 		echo -e "$1" 1>&2
 	else
-		grep '#' /proc/$$/fd/255 |sed -n '/^#HELPME_START/,/^#HELPME_END/p' \
-			| grep -v "^#HELPME_" | sed -e "s/#//" | tr -s '\t' 1>&2
+		grep '#@' /proc/$$/fd/255 \
+			| sed -n '/^#@ HELP_START/,/^#@ HELP_END/p' \
+			| grep -v "^#@ HELP_" \
+			| sed "
+				s/^#@//;
+				s/) #@ =/=/;
+				s/) #@ /\n\t\t/;
+				s/\t#@ /\t/;
+				s/ \+/ /;
+				s/^\t\t/\t/;
+				s/^ //" \
+			| sed "
+				s/\t/    /g;
+				s/ | /, /"
 	fi
-	kill 0
+	Pgid=$(ps -o pgid= $$ | tr -d " ")
+	[ $(cat /proc/$Pgid/task/$Pgid/children | wc -w) -lt 2 ] \
+		&& exit 1 \
+		|| kill 0
 }
+
 function hash_command {
-	hash $1 &> /dev/null || helpme "ERR-008: missing command $1"
+	hash $1 &> /dev/null || die "ERR-008: missing command $1"
 }
+
 ArchiveFreq=""
 CloneStyle=hardlink
 Keep=""
@@ -22,48 +40,72 @@ Remove=""
 Updatedb=NO
 ArgList=$@
 OptShort="hvn:c:a:s:r:k:d"
-OptLong="help,version,num-of-backups:clone-style:,archive:,source:,removal-percentage:,keep:,updatedb"
+OptLong="help,version,num-of-backups:clone-style:,archive:,source:\
+,removal-percentage:,keep:,updatedb"
 Opts=$(getopt -o $OptShort --long $OptLong -n daisync -- "$@")
 eval set -- "$Opts"
 while [ $# -gt 0 ]
 do
 	case "$1" in
-#HELPME_START
-#NAME
-#	daisync, a time-machine backup tool
-#EXAMPLE
-#	mkdir -p backup1/0000; daisync -c reflink -s someone@localhost:dir1/ backup1
-#	mkdir -p backup2/0000; daisync -s someone@localhost:"dir1\ dir2" backup2
-#SYNOPSIS
-#	daisync [OPTION]... DEST
-#DESCRIPTION
-		-h | --help) #print help information
-			helpme ;;
-		--version) #print version information
-			helpme "20240406" ;;
-		-v )	#verbose output
+#@ HELP_START
+#@ NAME
+#@ 	daisync, a time-machine backup tool
+#@ EXAMPLE
+#@ 	mkdir -p backup1/0000; daisync -c reflink -s someone@localhost:dir1/ backup1
+#@ 	mkdir -p backup2/0000; daisync -s someone@localhost:"dir1\ dir2" backup2
+#@ SYNOPSIS
+#@ 	daisync [OPTION]... DEST
+#@ DESCRIPTION
+		-h | --help) #@ Print this help information.
+			die ;;
+		--version) #@ Print version information.
+			die "20260111" ;;
+		-v )	#@ Enable verbose output.
 			set -x
 			shift ;;
-		-n | --num-of-backups)	#NUM, maximum number of transient backups, default 10
-			let Num=$2 || helpme "ERR-001: invalid number for -n: $2"
+		-n | --num-of-backups) #@ =[NUM]
+			#@ Maximum number of transient backups to keep.
+			#@ Default: 10
+			let Num=$2 || die "ERR-001: invalid number for -n: $2"
 			shift 2 ;;
-		-c | --clone-style)	#hardlink/reflink/none. Default is 'hardlink', unchanged files are hard-linked across all backups. With 'reflink', 'cp --reflink' are used prior to 'rsync', which doesn't support reflink yet as of 20020326. With 'none', unchanged files are not cloned and are only in 0000
+		-c | --clone-style) #@ =[STYLE]
+			#@ Clone Style: hardlink/reflink/none
+			#@ Default is 'hardlink', unchanged files are hard-linked across
+			#@ backups.
+			#@ With 'reflink' 'cp --reflink' is used before 'rsync'
+			#@ (note: rsync itself still does not support reflinks as of 2026).
+			#@ With 'none', unchanged files are not cloned and exist only in
+			#@ '0000'.
 			CloneStyle=$2
 			shift 2 ;;
-		-a | --archive)	#weekly/monthly/yearly, interval of permanent backups
-			[ "$2" = "weekly" -o "$2" = "monthly" -o "$2" = "yearly" ] || helpme "ERR-002: invalid paramter: -a $2"
+		-a | --archive) #@ =[INTERVAL]
+			#@ create permanent backups at given interval: weekly/monthly/yearly
+			[ "$2" = "weekly" -o "$2" = "monthly" -o "$2" = "yearly" ] \
+				|| die "ERR-002: invalid paramter: -a $2"
 			ArchiveFreq=$2
 			shift 2 ;;
-		-s | --source)	#SOURCE, such as "SERVER1:/home", "-e 'ssh -p 22' SERVER1:/home", "--exclude=*-excluded-from-daisync SERVER:/home". SOURCE is directly passed to rsync, can be local, rsync:// or rsync over remote shell, including ssh and rsh. Multiple '-s' are supported to backup some setup such as gluster storage nodes
+		-s | --source) #@ =[SOURCE]
+			#@ Source passed directly to rsync. be be specified multiple times.
+			#@ Examples: 
+			#@ "SERVER1:/home"
+			#@ "-e 'ssh -p 22' SERVER1:/home"
+			#@ "--exclude=*-excluded-from-daisync SERVER:/home"
+			#@ SOURCE can be local, rsync:// or rsync over remote shell
 			Sources+=("$2")
 			shift 2 ;;
-		-r | --removal-percentage)	#PERCENTAGE, see '-k' below
-			let Remove=$2 || helpme "ERR-005: invalid number for -r: $2"
+		-r | --removal-percentage) #@ =[PERCENTAGE]
+			#@ Target maximum disk usage percentage. See '-k'.
+			let Remove=$2 || die "ERR-005: invalid number for -r: $2"
 			shift 2 ;;
-		-k | --keep) #KEEP, keep removing the oldest transient backup until the DEST storage usage is below PERCENTAGE or there are only KEEP of backups left
-			let Keep=$2 || helpme "ERR-006: invalid number for -k: $2"
+		-k | --keep) #@ =[KEEP]
+			#@ Keep removing the oldest transient backups until:
+			#@ - disk usage is below PERCENTAGE, or
+			#@ - only KEEP of backups remain
+			let Keep=$2 || die "ERR-006: invalid number for -k: $2"
 			shift 2 ;;
-		-d | --updatedb)	#generate locate database to find file very quickly. A sample command of finding file is 'locate -d DEST/0000/.daisync-locate.db myfile'
+		-d | --updatedb) #@ Generate a locate database for fast file lookup
+			#@ Example:
+			#@ 'locate -d DEST/0000/.daisync-locate.db myfile'
 			hash_command updatedb
 			Updatedb=YES
 			shift 1 ;;
@@ -72,14 +114,14 @@ do
 			break ;;
 		*)
 			break ;;
-#AUTHOR
-#	Manhong Dai, MNI, U of Michigan
-#COPYRIGHT
-#	Copyright © 2002-2022 University of Michigan. License GPLv3+: GNU
-#	GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
-#	This is free software: you are free to change and redistribute it.
-#	There is NO WARRANTY, to the extent permitted by law.
-#HELPME_END
+#@ AUTHOR
+#@ 	Manhong Dai, MNI, U of Michigan
+#@ COPYRIGHT
+#@ 	Copyright © 2002-2026 University of Michigan. License GPLv3+: GNU
+#@ 	GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
+#@ 	This is free software: you are free to change and redistribute it.
+#@ 	There is NO WARRANTY, to the extent permitted by law.
+#@ HELP_END
 	esac
 done
 
@@ -92,26 +134,31 @@ then
 	Link="${Link} --reflink=always"
 elif [ "$CloneStyle" != "none" ] 
 then
-	helpme "ERR-016: invalid parameter for -c: $2"
+	die "ERR-016: invalid parameter for -c: $2"
 fi
 for Cmd in flock rsync fuser df
 do
 	hash_command $Cmd
 done
 set +u
-[ ${#Sources[@]} -gt 0 ] || helpme "ERR-007: missing -s"
+[ ${#Sources[@]} -gt 0 ] || die "ERR-007: missing -s"
 set -u
-[ $# -eq 1 ] || helpme "ERR-009: missing DEST"
+[ $# -eq 1 ] || die "ERR-009: missing DEST"
 Dest=$1
-[ -d "$Dest" ] || helpme "ERR-010: no such a directory '$Dest'"
-[ -d "$Dest/0000" ] || helpme "ERR-011: run 'mkdir -p $Dest/0000' to explicitly initialize \"$Dest\" as a daisync directory"
-[ -z "$Remove" -a -z "$Keep" ] || [ -n "$Remove" -a -n "$Keep" ] || helpme "ERR-013: -k and -r need be used together"
-[ ${#Sources[@]} -eq 1 -o "$CloneStyle" = "hardlink" ] || helpme "ERR-014: multiple -s can work with '-c hardlink' only"
+[ -d "$Dest" ] || die "ERR-010: no such a directory '$Dest'"
+[ -d "$Dest/0000" ] \
+	|| die "ERR-011: run 'mkdir -p $Dest/0000' to explicitly initialize \
+\"$Dest\" as a daisync directory"
+[ -z "$Remove" -a -z "$Keep" ] \
+	|| [ -n "$Remove" -a -n "$Keep" ] \
+	|| die "ERR-013: -k and -r need be used together"
+[ ${#Sources[@]} -eq 1 -o "$CloneStyle" = "hardlink" ] \
+	|| die "ERR-014: multiple -s can work with '-c hardlink' only"
 (
 	if ! flock -n 77
 	then
 		fuser "$Dest/.daisync-lock"
-		helpme "ERR-015: a daisync is still running, process id is above"
+		die "ERR-015: a daisync is still running, process id is above"
 	fi
 	echo "[$(date '+%F %H:%M:%S')]#daisync begin (daisync $ArgList)"
 	if [ $Num -gt 1 ]
@@ -133,15 +180,17 @@ Dest=$1
 		then
 			touch -a "$Dest/0000/.daisync-log"
 			mkdir -p "$Dest/.daisync-reflink"
-			if ! cp -a --reflink=always "$Dest/0000/.daisync-log" "$Dest/.daisync-reflink"
+			if ! cp -a --reflink=always "$Dest/0000/.daisync-log" \
+                "$Dest/.daisync-reflink"
 			then
 				rm -r "$Dest/.daisync-reflink"
-				helpme "ERR-017: \"$Dest\" doesn't support reflink. Try the latest version of xfs, btrfs, cifs, nfs 4.2, etc."
+				die "ERR-017: \"$Dest\" doesn't support \
+reflink. Try the latest version of xfs, btrfs, cifs, nfs 4.2, etc."
 			fi
 			cp -au --reflink=always "$Dest/0000/." "$Dest/.daisync-reflink"
 			mv "$Dest/.daisync-reflink" "$Dest/.daisync"
 		else
-			helpme "ERR-018"
+			die "ERR-018"
 		fi
 	fi
 	rm -f "$Dest/.daisync/.daisync-df"
@@ -185,7 +234,8 @@ Dest=$1
 			Params="-a"
 		fi
 		[ ${#Sources[@]} -eq 1 ] && Params="$Params --delete"
-		[ -f "$Dest/.daisync-exclude-from" ] && Params="$Params --exclude-from=$Dest/.daisync-exclude-from"
+		[ -f "$Dest/.daisync-exclude-from" ] \
+				&& Params="$Params --exclude-from=$Dest/.daisync-exclude-from"
 		echo "[$(date '+%F %H:%M:%S')]#rsync $Params \"$Src\" \"$Dest/.daisync\""
 		set +e
 		bash -c "rsync $Params $Src \"$Dest/.daisync\""
@@ -194,13 +244,14 @@ Dest=$1
 		if [ $RsyncRtn -ne 0 -a $RsyncRtn -ne 24 ]
 		then
 			wait
-			helpme "ERR-012: rsync '$Src' failed with code $RsyncRtn"
+			die "ERR-012: rsync '$Src' failed with code $RsyncRtn"
 		fi
 	done
 	if [ "$Updatedb" = "YES" ]
 	then
 		echo "[$(date '+%F %H:%M:%S')]#create locate database"
-		updatedb -l no -o "$Dest/.daisync/.daisync-locate.db" -U "$(realpath "$Dest/.daisync")"
+		updatedb -l no -o "$Dest/.daisync/.daisync-locate.db" \
+			-U "$(realpath "$Dest/.daisync")"
 		chmod 400 "$Dest/.daisync/.daisync-locate.db"
 	fi
 	df -Pm "$Dest" > "$Dest/.daisync/.daisync-df"
