now log is not moved if non-zero returned

diff --git a/daisync b/daisync
--- a/daisync
+++ b/daisync
@@ -73,7 +73,7 @@ do
 		*)
 			break ;;
 #VERSION
-#	20210718
+#	20210724
 #COPYRIGHT
 #	Developed by Manhong Dai, https://github.com/daimh/daisync
 #	Copyright © 2021 University of Michigan. License GPLv3+: GNU GPL version 3 or later.
@@ -96,166 +96,165 @@ DEST=$1
 [ -z "$REMOVE" -a -n "$KEEP" ] && helpme "ERR-013: -r is missing as -k is specified"
 [ -n "$REMOVE" -a -z "$KEEP" ] && helpme "ERR-014: -k is missing as -r is specified"
 [ ${#SOURCES[@]} -eq 1 -o "$INCREMENTAL" != "YES" ] || helpme "ERR-015: multiple -s cannot work with -I"
-
 (
-if ! flock -n 77
-then
-	fuser "$DEST/.daisync-lock"
-	echo "A previous daisync is still running, process id is above"
-	exit 222
-fi
-echo "[$(date '+%F %H:%M:%S')]#daisync begin (daisync $ARGLIST)"
-if [ $NUM -gt 1 ]
-then
-	((LAST=NUM-1))
-	LAST=$(printf "%04d" $LAST)
-fi
-if [ ! -d "$DEST/.daisync" ] 
-then
-	if [ "$INCREMENTAL" != "YES" -o ! -d "$DEST/0000" ]
+	if ! flock -n 77
 	then
-		mkdir "$DEST/.daisync"
-	else
-		mv "$DEST/0000" "$DEST/.daisync"
-		mkdir "$DEST/0000"
-		mv "$DEST/.daisync/.daisync-*" "$DEST/0000/" 2> /dev/null || :
+		fuser "$DEST/.daisync-lock"
+		helpme "ERR-016: a previous daisync is still running, process id is above"
 	fi
-fi
-rm -f "$DEST/.daisync/.daisync-df"
-if [ "$REMOVE" != "" ]
-then
-	for ((SLEEP=1; ;SLEEP++))
-	do
-		ps $$ &> /dev/null || break
-		((CUR_DFPCT=$(df -P "$DEST" | tail -n 1 |awk '{print $5}' | sed -e "s/%//") ))
-		if [ $CUR_DFPCT -ge $REMOVE ]
+	echo "[$(date '+%F %H:%M:%S')]#daisync begin (daisync $ARGLIST)"
+	if [ $NUM -gt 1 ]
+	then
+		((LAST=NUM-1))
+		LAST=$(printf "%04d" $LAST)
+	fi
+	if [ ! -d "$DEST/.daisync" ] 
+	then
+		if [ "$INCREMENTAL" != "YES" -o ! -d "$DEST/0000" ]
 		then
-			(( CUR_BKNUM=$( (cd $DEST && ls -d ???? .daisync 2>/dev/null ) | wc -l ) ))
-			[[ $CUR_BKNUM -le $KEEP ]] && break
-			LAST=$( (cd $DEST && ls -d ???? | grep -v 0000) | sort -r | head -n 1 )
-			if [ -n "$LAST" ]
+			mkdir "$DEST/.daisync"
+		else
+			mv "$DEST/0000" "$DEST/.daisync"
+			mkdir "$DEST/0000"
+			mv "$DEST/.daisync/.daisync-*" "$DEST/0000/" 2> /dev/null || :
+		fi
+	fi
+	rm -f "$DEST/.daisync/.daisync-df"
+	if [ "$REMOVE" != "" ]
+	then
+		for ((SLEEP=1; ;SLEEP++))
+		do
+			ps $$ &> /dev/null || break
+			((CUR_DFPCT=$(df -P "$DEST" | tail -n 1 |awk '{print $5}' | sed -e "s/%//") ))
+			if [ $CUR_DFPCT -ge $REMOVE ]
 			then
-				echo "[$(date '+%F %H:%M:%S')]#daisync removing $LAST"
-				rm -rf "$DEST/$LAST" 
-				continue
+				(( CUR_BKNUM=$( (cd $DEST && ls -d ???? .daisync 2>/dev/null ) | wc -l ) ))
+				[[ $CUR_BKNUM -le $KEEP ]] && break
+				LAST=$( (cd $DEST && ls -d ???? | grep -v 0000) | sort -r | head -n 1 )
+				if [ -n "$LAST" ]
+				then
+					echo "[$(date '+%F %H:%M:%S')]#daisync removing $LAST"
+					rm -rf "$DEST/$LAST" 
+					continue
+				fi
+			elif [ ! -d "$DEST/.daisync" ]
+			then
+				break
 			fi
-		elif [ ! -d "$DEST/.daisync" ]
-		then
-			break
-		fi
-		if [ $SLEEP -gt 60 ] 
-		then
-			sleep 60
-		else
-			sleep $SLEEP
-		fi
-	done
-fi &
-
-mapfile -t SOURCES < <(shuf -e -- "${SOURCES[@]}")
-for SRC in "${SOURCES[@]}"
-do
-	if [ "$INCREMENTAL" = "YES" ]
-	then
-		PARAMS="-ab --backup-dir=../0000"
-	else
-		PARAMS="-a --link-dest=../0000"
-	fi
-	[ ${#SOURCES[@]} -eq 1 ] && PARAMS="$PARAMS --delete"
-	[ -f "$DEST/.daisync-exclude-from" ] && PARAMS="$PARAMS --exclude-from=$DEST/.daisync-exclude-from"
-	echo "[$(date '+%F %H:%M:%S')]#rsync $PARAMS \"$SRC\" \"$DEST/.daisync\""
-	set +e
-	bash -c "rsync $PARAMS $SRC \"$DEST/.daisync\""
-	RSYNC_RTN=$?
-	[ $RSYNC_RTN -eq 0 -o $RSYNC_RTN -eq 24 ] || helpme "ERR-012: rsync '$SRC' failed with code $RSYNC_RTN"
-	set -e
-done
-if [ "$LINK" != "" ]
-then
-	echo "[$(date '+%F %H:%M:%S')]#relinking moved files that is greater than $LINK MB"
-	find "$DEST/.daisync" -type f -size +${LINK}M -links 1 -print0 | while read -d $'\0' FNEW
-	do
-		HASH=$(sha512sum "$FNEW" |cut -c 1-128)
-		read STATU STATG STATS STATY < <(stat -c "%u %g %s %Y" "$FNEW")
-		find "$DEST/0000" -type f -uid $STATU -gid $STATG -size ${STATS}c -exec bash -c "
-			if [ \"$HASH\" = \"\$(sha512sum \"{}\" |cut -c 1-128)\" -a \"\$(stat -c %Y \"{}\")\" = \"$STATY\" ]
+			if [ $SLEEP -gt 60 ] 
 			then
-				echo \"[\$(date '+%F %H:%M:%S')]#linking: '{}'\" \"to\" \"'$FNEW'\"
-				ln -f \"{}\" '$FNEW'
+				sleep 60
 			else
-				exit 1
-			fi" \; -quit
-	done
-fi
-if [ "$UPDATEDB" = "yes" ]
-then
-	echo "[$(date '+%F %H:%M:%S')]#create locate database"
-	updatedb -l no -o "$DEST/.daisync/.daisync-locate.db" -U "$(realpath "$DEST/.daisync")"
-	chmod 400 "$DEST/.daisync/.daisync-locate.db"
-fi
-df -Pm "$DEST" > "$DEST/.daisync/.daisync-df"
-((NUM--))
-for IDX in $(seq -f %04g $NUM -1 0)
-do
-	if [ -d "$DEST/$IDX" ]
-	then
-		if [ "$IDX" = "$(printf "%04d" $NUM)" ]
-		then
-			rm -rf "$DEST/$IDX"
-		else
-			mv "$DEST/$IDX" "$DEST/$PREV"
-		fi
-	fi
-	PREV=$IDX
-done
-mv "$DEST/.daisync" "$DEST/0000"
-wait
-
-if [ "$ARCHIVE" != "" ]
-then
-	(( NOW=$(date +%s) ))
-	if [ "$ARCHIVE" = "weekly" ]
-	then
-		(( OFFSET=$(date --date="@$NOW" +%w) ))
-		(( START=$NOW - $OFFSET * 3600 * 24 ))
-	elif [ "$ARCHIVE" = "monthly" ]
-	then
-		(( OFFSET=$(date --date="@$NOW" +%_d) ))
-		(( OFFSET-- ))
-		(( START=$NOW - $OFFSET * 3600 * 24 ))
-	elif [ "$ARCHIVE" = "yearly" ]
-	then
-		(( OFFSET=$(date --date="@$NOW" +%_j) ))
-		(( OFFSET-- ))
-		(( START=$NOW - $OFFSET * 3600 * 24 ))
-	fi
-	HAS_ARCHIVE=NO
-	for ((DT=$START; DT<=$NOW; DT+=3600 * 24))
+				sleep $SLEEP
+			fi
+		done
+	fi &
+	mapfile -t SOURCES < <(shuf -e -- "${SOURCES[@]}")
+	for SRC in "${SOURCES[@]}"
 	do
-		DAY=$(date --date="@$DT" +%F)
-		if ls "$DEST"/$DAY-??-??-?? &> /dev/null
-		then
-			HAS_ARCHIVE=YES
-			break
-		fi
-	done
-	if [ "$HAS_ARCHIVE" = "NO" ]
-	then
-		NOW=$(date --date="@$NOW" +%F-%H-%M-%S)
-		echo "[$(date '+%F %H:%M:%S')]#creating $ARCHIVE archive"
-		echo $NOW > "$DEST/0000/.daisync-archived"
 		if [ "$INCREMENTAL" = "YES" ]
 		then
-			cp -apr "$DEST/0000" "$DEST/$NOW"
+			PARAMS="-ab --backup-dir=../0000"
 		else
-			cp -aprl "$DEST/0000" "$DEST/$NOW"
+			PARAMS="-a --link-dest=../0000"
+		fi
+		[ ${#SOURCES[@]} -eq 1 ] && PARAMS="$PARAMS --delete"
+		[ -f "$DEST/.daisync-exclude-from" ] && PARAMS="$PARAMS --exclude-from=$DEST/.daisync-exclude-from"
+		echo "[$(date '+%F %H:%M:%S')]#rsync $PARAMS \"$SRC\" \"$DEST/.daisync\""
+		set +e
+		bash -c "rsync $PARAMS $SRC \"$DEST/.daisync\""
+		RSYNC_RTN=$?
+		[ $RSYNC_RTN -eq 0 -o $RSYNC_RTN -eq 24 ] || helpme "ERR-012: rsync '$SRC' failed with code $RSYNC_RTN"
+		set -e
+	done
+	if [ "$LINK" != "" ]
+	then
+		echo "[$(date '+%F %H:%M:%S')]#relinking moved files that is greater than $LINK MB"
+		find "$DEST/.daisync" -type f -size +${LINK}M -links 1 -print0 | while read -d $'\0' FNEW
+		do
+			HASH=$(sha512sum "$FNEW" |cut -c 1-128)
+			read STATU STATG STATS STATY < <(stat -c "%u %g %s %Y" "$FNEW")
+			find "$DEST/0000" -type f -uid $STATU -gid $STATG -size ${STATS}c -exec bash -c "
+				if [ \"$HASH\" = \"\$(sha512sum \"{}\" |cut -c 1-128)\" -a \"\$(stat -c %Y \"{}\")\" = \"$STATY\" ]
+				then
+					echo \"[\$(date '+%F %H:%M:%S')]#linking: '{}'\" \"to\" \"'$FNEW'\"
+					ln -f \"{}\" '$FNEW'
+				else
+					exit 1
+				fi" \; -quit
+		done
+	fi
+	if [ "$UPDATEDB" = "yes" ]
+	then
+		echo "[$(date '+%F %H:%M:%S')]#create locate database"
+		updatedb -l no -o "$DEST/.daisync/.daisync-locate.db" -U "$(realpath "$DEST/.daisync")"
+		chmod 400 "$DEST/.daisync/.daisync-locate.db"
+	fi
+	df -Pm "$DEST" > "$DEST/.daisync/.daisync-df"
+	((NUM--))
+	for IDX in $(seq -f %04g $NUM -1 0)
+	do
+		if [ -d "$DEST/$IDX" ]
+		then
+			if [ "$IDX" = "$(printf "%04d" $NUM)" ]
+			then
+				rm -rf "$DEST/$IDX"
+			else
+				mv "$DEST/$IDX" "$DEST/$PREV"
+			fi
+		fi
+		PREV=$IDX
+	done
+	mv "$DEST/.daisync" "$DEST/0000"
+	wait
+	
+	if [ "$ARCHIVE" != "" ]
+	then
+		(( NOW=$(date +%s) ))
+		if [ "$ARCHIVE" = "weekly" ]
+		then
+			(( OFFSET=$(date --date="@$NOW" +%w) ))
+			(( START=$NOW - $OFFSET * 3600 * 24 ))
+		elif [ "$ARCHIVE" = "monthly" ]
+		then
+			(( OFFSET=$(date --date="@$NOW" +%_d) ))
+			(( OFFSET-- ))
+			(( START=$NOW - $OFFSET * 3600 * 24 ))
+		elif [ "$ARCHIVE" = "yearly" ]
+		then
+			(( OFFSET=$(date --date="@$NOW" +%_j) ))
+			(( OFFSET-- ))
+			(( START=$NOW - $OFFSET * 3600 * 24 ))
+		fi
+		HAS_ARCHIVE=NO
+		for ((DT=$START; DT<=$NOW; DT+=3600 * 24))
+		do
+			DAY=$(date --date="@$DT" +%F)
+			if ls "$DEST"/$DAY-??-??-?? &> /dev/null
+			then
+				HAS_ARCHIVE=YES
+				break
+			fi
+		done
+		if [ "$HAS_ARCHIVE" = "NO" ]
+		then
+			NOW=$(date --date="@$NOW" +%F-%H-%M-%S)
+			echo "[$(date '+%F %H:%M:%S')]#creating $ARCHIVE archive"
+			echo $NOW > "$DEST/0000/.daisync-archived"
+			if [ "$INCREMENTAL" = "YES" ]
+			then
+				cp -apr "$DEST/0000" "$DEST/$NOW"
+			else
+				cp -aprl "$DEST/0000" "$DEST/$NOW"
+			fi
 		fi
 	fi
-fi
-echo "[$(date '+%F %H:%M:%S')]#daisync end"
+	echo "[$(date '+%F %H:%M:%S')]#daisync end"
 ) 77> "$DEST/.daisync-lock" 2>&1 | tee "$DEST/.daisync-log.$$"
-mv "$DEST/.daisync-log.$$" "$DEST/0000/.daisync-log"
-if [ -f "$DEST/0000/.daisync-archived" ]
-then
-	ln "$DEST/0000/.daisync-log" "$DEST/$(cat "$DEST/0000/.daisync-archived")/"
+RTN=$?
+if [ $RTN -eq 0 ]
+then 
+	mv "$DEST/.daisync-log.$$" "$DEST/0000/.daisync-log"
+	[ -f "$DEST/0000/.daisync-archived" ] && ln "$DEST/0000/.daisync-log" "$DEST/$(cat "$DEST/0000/.daisync-archived")/"
 fi
+exit $RTN
